USE CRUD

CREATE TABLE PRODUCTOS (
	ID INT IDENTITY(1,1),
	NOMBRE VARCHAR(40),
	MARCA VARCHAR(40),
	PRECIO FLOAT(15),
	UNIDAD VARCHAR(40),
	EXISTENCIA FLOAT(5),
	ESTATUS BIT
);

INSERT INTO PRODUCTOS (NOMBRE, MARCA, PRECIO, UNIDAD, EXISTENCIA, ESTATUS) VALUES ('PLUMA', 'BIC', 15, 'DFR', 17, 1)
INSERT INTO PRODUCTOS (NOMBRE, MARCA, PRECIO, UNIDAD, EXISTENCIA, ESTATUS) VALUES ('SACAPUNTAS', 'BIC', 10, 'VGT', 50, 1)
INSERT INTO PRODUCTOS (NOMBRE, MARCA, PRECIO, UNIDAD, EXISTENCIA, ESTATUS) VALUES ('CUADERNO', 'BIC', 30, 'LPT', 18, 1)
INSERT INTO PRODUCTOS (NOMBRE, MARCA, PRECIO, UNIDAD, EXISTENCIA, ESTATUS) VALUES ('CORRECTOR', 'BIC', 15, 'BTR', 27, 1)

SELECT * FROM PRODUCTOS

SELECT * FROM PRODUCTOS WHERE ESTATUS = 1

DELETE FROM PRODUCTOS WHERE ID = 1

DROP TABLE PRODUCTOS

UPDATE PRODUCTOS SET NOMBRE='SACAPUNTAS', PRECIO=10 WHERE ID=2

UPDATE PRODUCTOS SET ESTATUS=0 WHERE ID=2